# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  ## option for vagrant-vbguest
  ## install plugin with: vagrant plugin install vagrant-vbguest
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.hostname = "centos7"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "/home/boogy", "/share"

  ## configuration de la machine virtuelle
  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos7"
    vb.memory = 1024
    vb.cpus = 1
    vb.gui = false
  end

  ## script inline pour le provisionning
  ## exemple: vagrant up --provision
  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
    yum install -y epel-release debootstrap perl libvirt lxc lxc-templates lxc-extra

    yum install -y httpd tree

    systemctl status lxc.service
    systemctl start lxc.service
    systemctl start libvirtd
    systemctl status lxc.service

  SHELL
end
