#!/usr/bin/env bash
export PS1="${debian_chroot:+($debian_chroot)}\[\033[01;34m\]\w\[\033[00m\]\n\[\033[01;32m\]\u@\h\[\033[00m\]"
export PS1="${PS1}\[\033[1;33m\]\$(git-branch-prompt)\[\033[0m\] \$ "
