#!/bin/sh

# Gives a dmenu prompt to search DuckDuckGo.
# Without input, will open DuckDuckGo.com.
# Anything else, it search it.
BROWSER=chromium

pgrep -x dmenu && exit

# choice=$(echo "🦆" | dmenu -i -p "Search DuckDuckGo:") || exit 1
choice=$(echo "DuckDuckGo " | dmenu -i -p "Search DuckDuckGo:") || exit 1

if [ "$choice" = "DuckDuckGo "  ]; then
    $BROWSER "https://duckduckgo.com"
else
    $BROWSER "https://duckduckgo.com/?q=$choice&t=ffab&atb=v1-1"
fi
