$script = <<-SCRIPT
export DEBIAN_FRONTEND=noninteractive

apt update
apt -yq install software-properties-common apt-transport-https python-dev \
python-pip python3-dev python3-pip python3-cryptography python-openssl \
python-virtualenv virtualenvwrapper make cmake socat p7zip rar unrar \
unzip strace ltrace bzip2 rdesktop gcc mysql-server apache2 \
php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip

apt autoclean -y
apt autoremove -y
apt -y install -f

## vagrant user commands
sudo -u vagrant -H bash << EOF
pip install -U --user pipenv
EOF

SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "ubuntu1804"

    # config.vm.network "forwarded_port", guest: 80, host: 8080, protocol: "tcp"
    # config.vm.network "forwarded_port", guest: 443, host: 8443, protocol: "tcp"
    # config.vm.network "public_network", type: "dhcp", bridge: "eth0"
    config.vm.network "private_network", type: "dhcp"

    config.vm.provider "virtualbox" do |v|
        v.name = "ubuntu18dev"
        v.memory = 2048
        v.cpus = 2
    end
    config.vm.provision "shell", inline: $script
    config.vm.synced_folder "/home/boogy", "/home/vagrant/share/"
end

