#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
#yabai -m config external_bar                 off:45:0
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float #off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9
yabai -m config window_border                off
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xff3bff3b
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       float
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   2

# mission-control desktop labels
yabai -m space 1 --label main
yabai -m space 2 --label web
yabai -m space 3 --label term
yabai -m space 4 --label mail
yabai -m space 5 --label vms
yabai -m space 6 --label docs
yabai -m space 7 --label files
yabai -m space 8 --label screens
yabai -m space 9 --label calls
yabai -m space 0 --label chat

# specific space settings
yabai -m config --space main    layout float
yabai -m config --space web     layout float
yabai -m config --space code    layout float
yabai -m config --space mail    layout float
yabai -m config --space vms     layout float
yabai -m config --space docs    layout bsp
yabai -m config --space files   layout float
yabai -m config --space screens layout float
yabai -m config --space calls   layout float
yabai -m config --space chat    layout float

# window rules
# yabai -m rule --add app="^Firefox$" space=web
# yabai -m rule --add app="^iTerm2$"  space=term
# yabai -m rule --add app="^Spotify$" space=chat

## exclude applications from being managed by yabai
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off border=off
yabai -m rule --add label="Finder" app="Finder" manage=off border=off #title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off border=off
yabai -m rule --add label="Karabiner-Elements" app="^Karabiner-Elements$" manage=off border=off
yabai -m rule --add label="Karabiner-EventViewer" app="^Karabiner-EventViewer$" manage=off border=off
yabai -m rule --add label="Karabiner-MultitouchExtension" app="^Karabiner-MultitouchExtension$" manage=off border=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off border=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off border=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off border=off
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off border=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off border=off
yabai -m rule --add label="VLC" app="VLC" manage=off border=off
yabai -m rule --add label="Zoom" app="^Zoom$" manage=off border=off

## Remove borders
yabai -m rule --add app="^Firefox$" border=off
yabai -m rule --add app="^Safari$" border=off
yabai -m rule --add app="^Chrome$" border=off

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
# yabai -m signal --add event=window_destroyed action="echo \"destroyed window with id \$YABAI_WINDOW_ID\""
# yabai -m signal --add event=space_changed action="echo \"changed space \$YABAI_RECENT_SPACE_ID -> \$YABAI_SPACE_ID\""
# yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

echo "yabai configuration loaded.."
