#!/usr/bin/env bash

## Remove all existing rules before loading
bspc rule -r "*"

## Set environment path
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

## BSPWM configuration
## longest_side || alternate || spiral
bspc config automatic_scheme              longest_side
bspc config split_ratio                   0.50
bspc config border_width                  2
bspc config window_gap                    6
bspc config top_padding                   0
bspc config bottom_padding                20
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                true
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         false
bspc config pointer_follows_monitor       true
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true
bspc config center_pseudo_tiled           true
bspc config ignore_ewmh_focus             false

## commnand: xmodmap -pke | xmodmap -pm
## shift, control, lock, mod1, mod2, mod3, mod4, mod5
## mod1=Alt, mod4=super, mod5=AltGr
bspc config pointer_modifier mod1
bspc config pointer_action1  move
bspc config pointer_action2  resize_side
bspc config pointer_action3  resize_corner

## BSPWM Colors
bspc config normal_border_color   "#4c566a"
bspc config active_border_color   "#1e1e1e"
bspc config focused_border_color  "#3bff3b"
bspc config presel_feedback_color "#5e81ac"

## BSPWM monitors
"$(which bspwm-setup-monitors.sh)" &

## Script for external rules
bspc config external_rules_command "$(which bspwm-external-rules.sh)"

## Send to desktop
bspc rule -a firefox           desktop=2  state=tiled --one-shot
bspc rule -a Vmware            desktop=5  state=tiled follow=on
bspc rule -a Hexchat           desktop=10 state=tiled follow=on

## Other floating windows
bspc rule -a mpv               state=floating center=on
bspc rule -a Blueman-manager   state=floating center=on
bspc rule -a Shutter           state=floating center=on
bspc rule -a Solaar            state=floating center=on
bspc rule -a Arandr            state=floating center=on
bspc rule -a Display           state=floating center=on
bspc rule -a KeePassXC         state=floating center=on
bspc rule -a Nautilus          state=floating center=on
bspc rule -a Pavucontrol       state=floating center=on

## Load session
. "$BSPWM_CONFIG/restore.cfg"
if [ -e "$BSPWM_STATE" ] ; then
    bspc wm --load-state "$BSPWM_STATE"
    bspc wm --adopt-orphans
    rm "$BSPWM_STATE"
fi

## AUTOSTART
"$(which bspwm-autostart.sh)" &

