#!/usr/bin/env bash

lock() {
    # i3lock --show-failed-attempts --color=#2f343f
    i3lock --show-failed-attempts --color=#2f343f --ignore-empty-password --lock-console
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && sudo systemctl suspend
        ;;
    hibernate)
        lock && sudo systemctl hibernate
        ;;
    reboot)
        sudo systemctl reboot
        ;;
    shutdown)
        sudo systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
