[colors.bright]
black = "#75715E"
blue = "#66D9EF"
cyan = "#2AA198"
green = "#A6E22E"
magenta = "#AE81FF"
red = "#F92672"
white = "#F9F9F5"
yellow = "#F4BF75"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#5D5B57"
blue = "#66D9EF"
cyan = "#2AA198"
green = "#A6E22E"
magenta = "#AE81FF"
red = "#F92672"
white = "#F9F8F5"
yellow = "#F4BF75"

[colors.primary]
background = "#191919"
foreground = "#d8dee9"
